name = "bullet/account-abstraction"
version = "0.0.1"
compiler = "v1.1.12"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'bullet/account-abstraction'"

[repository]
user = "bullet"
project = "account-abstraction"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.1"
source = "github"

[config.default]
bullet_hash = "totally_valid"
nonce_bullet_hash = "totally_valid_nonce"
proxy_hash = "valid_proxy"
stake_proxy_hash = "staking_proxy"
new_user_tx_hash = "new_guy_in_town"
new_user_output_index = 0
one_shot_tx_hash = "one_shot_one_kill"
one_shot_output_index = 0
one_shot_mint_hash = "the_best_mint_ever"
namespace = "Bullet"

[config.preview]
new_user_output_index = 21
one_shot_output_index = 0
namespace = "Bullet"

[config.preview.bullet_hash]
bytes = "ab2426d61eb0da0589670a308d5ce99bf2f0dcdb32257cdb7cbf333f"
encoding = "hex"

[config.preview.nonce_bullet_hash]
bytes = "2397463cdf1c6839faa69c50d075ef03df312b7e450aefd417e193d3"
encoding = "hex"

[config.preview.proxy_hash]
bytes = "e06e3d21a549bb46a8560fe929ffe7d1ea964b92b86d7ed16ea4f3a7"
encoding = "hex"

[config.preview.stake_proxy_hash]
bytes = "8c0d09fc8234a275398b9eed39a40f303901ff9d41dbe7c09b6005fd"
encoding = "hex"

[config.preview.new_user_tx_hash]
bytes = "0788cbca89f1a7442f0ed538d5d30ffee1014d367c1bbba4b13305b7bd8a36b7"
encoding = "hex"

[config.preview.one_shot_tx_hash]
bytes = "89618f8648db0e830dd3b5b6631c46b71360ccd9b64b9c9510486284cf44ba78"
encoding = "hex"

[config.preview.one_shot_mint_hash]
bytes = "28ac2d43665f9c5b46908532fd27783e0e45039415664d90b3043743"
encoding = "hex"
